// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANdPyCU4icxuPgPq-xetLd7uZhN0ajTOk',
    appId: '1:15086614704:web:6e93c3aaade896a6e3e375',
    messagingSenderId: '15086614704',
    projectId: 'tokopedia-1a24d',
    authDomain: 'tokopedia-1a24d.firebaseapp.com',
    storageBucket: 'tokopedia-1a24d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBZbfVRCadaPb5e5dKvULtXGtl_0iu8Kw',
    appId: '1:15086614704:android:3f93c59cbe1d2833e3e375',
    messagingSenderId: '15086614704',
    projectId: 'tokopedia-1a24d',
    storageBucket: 'tokopedia-1a24d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiRS2vKePsIM2W1XczcgKQRLOKss1DSU0',
    appId: '1:15086614704:ios:88230bf9e770b65ce3e375',
    messagingSenderId: '15086614704',
    projectId: 'tokopedia-1a24d',
    storageBucket: 'tokopedia-1a24d.appspot.com',
    iosClientId: '15086614704-icskulls3u5k9o1v77ka8n4se887bsfi.apps.googleusercontent.com',
    iosBundleId: 'com.tokopedia.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiRS2vKePsIM2W1XczcgKQRLOKss1DSU0',
    appId: '1:15086614704:ios:d9915911f7042f12e3e375',
    messagingSenderId: '15086614704',
    projectId: 'tokopedia-1a24d',
    storageBucket: 'tokopedia-1a24d.appspot.com',
    iosClientId: '15086614704-d7un5a8pu8rtj819s2tmj32o4t8h9uf8.apps.googleusercontent.com',
    iosBundleId: 'Tokopedia.tokopedia',
  );
}
